### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by JasonWeathersby** [mozdevs/CFPs#1]
"Using bots to help us find people who is in need help in other channels". Might want to change this sentence :)

**Comment by nickdesaulniers** [comment]
I need to work on rereading what I write.  Too many grammatical errors lately...
Since I've already submitted with the error, let's keep this version as is since if it's not accepted viewers can see that poor grammar might be a contributing factor.

**Comment by JasonWeathersby** [comment]
Sounds good, maybe we should have a draft folder, submitted and accepted

**Comment by nickdesaulniers** [comment]
check it ^ :beers:
